//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace back
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            this.tbVeiculos = new HashSet<tbVeiculos>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public string cpf { get; set; }
        public Nullable<int> tipo { get; set; }
        public string CNH { get; set; }
        public Nullable<System.DateTime> val_CNH { get; set; }
        public string telefone { get; set; }
        public string senha { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        public virtual ICollection<tbVeiculos> tbVeiculos { get; set; }
    }
}
