//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace back
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVeiculos
    {
        public tbVeiculos()
        {
            this.tbReservas = new HashSet<tbReservas>();
        }
    
        public int id { get; set; }
        public string modelo { get; set; }
        public string placa { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual ICollection<tbReservas> tbReservas { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
