//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maringa___Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbConsumo
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string combustivel { get; set; }
        public Nullable<double> distancia { get; set; }
        public Nullable<double> media { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<double> media_litro_gasto { get; set; }
        public Nullable<decimal> preco_para_percorrer { get; set; }
    }
}
