//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maringa___Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIMC
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> altura { get; set; }
        public Nullable<double> imc { get; set; }
        public string classificacao { get; set; }
    }
}
